export const GET_BLOG_DATA_REQUIEST = "GET_BLOG_DATA_REQUIEST"
export const GET_BLOG_DATA_SUCCESS = "GET_BLOG_DATA_SUCCESS"
export const GET_BLOG_DATA_FAIL = "GET_BLOG_DATA_FAIL"

export const ADD_BLOG_DATA_REQUIEST = "ADD_BLOG_DATA_REQUIEST"
export const ADD_BLOG_DATA_SUCCESS = "ADD_BLOG_DATA_SUCCESS"
export const ADD_BLOG_DATA_FAIL = "ADD_BLOG_DATA_FAIL"

export const DELETE_BLOG_DATA_REQUIEST = "DELETE_BLOG_DATA_REQUIEST"
export const DELETE_BLOG_DATA_SUCCESS = "DELETE_BLOG_DATA_SUCCESS"
export const DELETE_BLOG_DATA_FAIL = "DELETE_BLOG_DATA_FAIL"